version = 0.1
[default.deploy.parameters]
stack_name = "gossip-service"
resolve_s3 = true
s3_prefix = "gossip-service"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true

[native.deploy.parameters]
stack_name = "gossip-service-native"
s3_prefix = "gossip-service-native"
resolve_s3 = true
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []